### ISSUE TITLE
Guard Gem issue

### ISSUE THREAD

**Issue by Topkinsme** [Topkinsme/Color-Battle-Roles#19]
There is currently a edge case with what happens if a guard is in possession of a gem. Does the guard still die if the target is killed enough? Or does the gem protect them since the attack is redirected? That would mean the gem protection is shared between the target and the guard.

This is unclear, and if the gem trader rework doesn't fix it, might be a serious issue.

**Comment by 12Metatron** [comment]
the guard is now last layer of protection so it wont redirect attacks if king is protected by a gem or any other means. guard can still protect if it has a gem since it can not be roleblocked. guards protection is through redirection (with the strong attack conditions). so I think this issue is resolved. you can reopen it if I'm misinterpreting the question or there's something I'm not accounting for.
