### ISSUE TITLE
Princess Edge cases.

### ISSUE THREAD

**Issue by Topkinsme** [Topkinsme/Color-Battle-Roles#76]
What happens if 2 princesses tie? 
I reckon we give each princess 50% of the total cash and just announce both.

Also, does the princess reveal only reveal the role or the role along with the team?

**Comment by RainIsWater** [comment]
I agree with your idea to give each princess 50% of the total cash and announcing both of them. That feels like it would be the most fair for all sides.

I originally felt like only the Princess role should be revealed instead of the team but changed my mind- Currently both the Queen and the Princess are fairly dominant with the Prince being just bad. (I am aware that a buff is coming.) 

A small nerf to Princess with the role+team being visible might make it more even, especially for Jacks.

**Comment by Topkinsme** [comment]
I agree with whatever you said but I believe when I asked for opinions on Discord, @cryptidjayden said they preferred only the role being revealed. This might require a few more opinions.

**Comment by TheEighthDeadlySin** [comment]
It might be worth mentioning this, but I think we agreed on the fact that if a Sacrificial Lamb was tributed with a Princess also put on tribute by another team, the Princess dies?

**Comment by Topkinsme** [comment]
No, I think we agreed that the Sacrificial Lamb deaths are all Tribute Deaths, so the princess ability would activate if a sacrificial lamb died in said tribute. (Unless I'm misremembering things)

Thought yes it might be worth mentioning it here (and in sacrificial lamb)

**Comment by TheEighthDeadlySin** [comment]
To be completely honest, I kinda had a guess here, I didn't know whether it was the Princess dies or the Princess uses ability. I thought it was a bit more logical if the Sacrificial Lamb being tributed counted as the Sacrificial Lamb killing the others on tribute. I'll quickly have a look back to see what we agreed on though.

**Comment by TheEighthDeadlySin** [comment]
Couldn't find it, but I think we agreed on what you said Top
